# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f56d6fe21b73d5fce32c5a6b0adc8a7d8e99517c8c92001f6820230aff7efe758b69e13ec886c9327b5c7ed4032a68acda89994636986afd021102981f31e1fd

test:
  secret_key_base: 55dcd7ecb49aee681427bccffd4c27d0d7f367039175bd954e61c4a7a88cabdf7acf122a9ca78dc4a413b96bc852465956cff9258692503e0fbcbae166930908

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
